#ifndef CONFIG_CLIENT_H
#define CONFIG_CLIENT_H

#include "../common/config.h"

enum ConfigItem
{
	INTERFACE,
	SRC_ADDR,
	UNICAST_SET,
	MULTICAST_SET,
	UNICAST_64_SET,
	MULTICAST_64_SET,
	MAX_ADDR_UNICAST,
	MAX_ADDR_MULTICAST,
	MAX_ADDR_UNICAST_64,
	MAX_ADDR_MULTICAST_64,
	DEFAULT_ADDR_OFFER,
	UNICAST_LIFETIME,
	MULTICAST_LIFETIME,
	UNICAST_64_LIFETIME,
	MULTICAST_64_LIFETIME,
	RESERVE_LIFETIME,
	ACCEPT_RENEWAL,
	DEFAULT_MULTICAST,
	DEFAULT_64,
	AUTOASSIGN_OBJECTION,
	ENABLE_ALTERNATE_SET,
	NETWORK_ID,
	VENDOR,
	MAX_CONFIG_ITEM,
};


class ConfigServer : public Config
{
public:
	ConfigServer();
	~ConfigServer();
	int getMaxItem() {return MAX_CONFIG_ITEM;}
	bool check(const char *fname);
};

#endif
